---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(lubridate)
library(readxl)
```


Data Sets
```{r}
#MAHealth<-read_excel("~/Documents/NYU/Fall 2017/Stats Consulting/Policy Difussion/Data/MAHealthRankings.xlsx")
MAHealthdata<-read_excel("~/Documents/NYU/Fall 2017/Stats Consulting/CountyHealthRankingRawData.xlsx")
MAT21 <- read_excel("~/Documents/NYU/Fall 2017/Stats Consulting/MA21Clean.xlsx")
MACounty <- read_excel("~/Documents/NYU/Fall 2017/Stats Consulting/CountyTownMA.xlsx")
mayor<- read_excel("~/Documents/NYU/Fall 2017/Stats Consulting/Mayor_Council name_MA.xlsx")
```

Viewing Data Header
```{r}
head(MAHealthdata) #Junyan's MA Health data
head(MAT21) #T21 established counties
head(MACounty) #County Information in MA
```

Clean Data
```{r}
MAT21 <- MAT21[,c(2:3)]
head(MAT21)
```
pdata

```{r}
pdata <- with(MACTownHealth21_v3, expand.grid(T21year = seq(min(T21year, na.rm = TRUE), max(T21year, na.rm = TRUE)),id = unique(Name)))
View(pdata)
```


Left_Joins
```{r}
MACTown21 <- MACounty %>% left_join(MAT21, by = c("Name" = "Town"))
names(MACTown21)[6]<-"FormYear"

#MACTownHealth21_v1 <- MACTown21 %>% left_join(MAHealth, by = c("County", "County"))
MACTownHealth21_v2 <- MACTown21 %>% left_join(MAHealthdata, by = c("County", "County"))
head(MACTownHealth21_v2)

MACTownHealth21_v2$T21Date <- as.Date(MACTownHealth21_v2$T21Date) #get the T21 year
MACTownHealth21_v2$T21year <- year(MACTownHealth21_v2$T21Date)


names(mayor)[1]<-"Name"
MACTownHealth21_v3<- MACTownHealth21_v2 %>% left_join(mayor, by=c("Name","Name")) #merge the mayor data
MACTownHealth21_v3$mayor_ind<-1
MACTownHealth21_v3$mayor_ind[is.na(MACTownHealth21_v3$MAYOR)]=0



MACTownHealth21_intm <- unique(MACTownHealth21_v3[,c(1,36)])
names(pdata)[2]<-"Name"
MACTownHealth21_intm <- pdata %>% left_join(MACTownHealth21_intm, by = c("Name", "Name"))
colnames(MACTownHealth21_intm) <- c("year", "TownName", "Event")

MACTownHealth21_intm2<- mutate(MACTownHealth21_intm, Event = ifelse(Event < year, "2", ifelse(Event ==year,"1","0")))

MACTownHealth21_intm2[is.na(MACTownHealth21_intm2$Event),]$Event <- "0"

#merge to the main database
names(MACTownHealth21_intm2)[1]<-"Year"
names(MACTownHealth21_intm2)[2]<-"Name"
MACTownHealth21_v6<- MACTownHealth21_intm2 %>% left_join(MACTownHealth21_v3, by=c("Name","Year"))

```

Getting the Year of T21
```{r}

write.csv(MACTownHealth21_v6, "~/Documents/NYU/Fall 2017/Stats Consulting/MACTownHealth21_v5.csv")


#Don't run
attach(MACTownHealth21)
#Data needs to be fixed and cleaned or we need to crawl a more updated site
max(T21year, na.rm = TRUE)
min(T21year, na.rm = TRUE)
names(MACTownHealth21)
```
###Don't run####

Expand the data to get into Event History Analysis Form
```{r}
pdata <- with(MACTownHealth21_v3, expand.grid(T21year = seq(min(T21year, na.rm = TRUE), max(T21year, na.rm = TRUE)),id = unique(Name)))
View(pdata)
```



