---
title: "Distance Calculations"
output: html_notebook
---

We want to create the Euclidean distance matrix to see the ratio of other T21 towns in a 80/160 kilometer radius.

First, the matrix (borrowing the code from https://eurekastatistics.com/calculating-a-distance-matrix-for-geographic-points-using-r/):
```{r}
require(Imap)
require(dplyr)
require(tibble)

ReplaceLowerOrUpperTriangle <- function(m, triangle.to.replace){
   # If triangle.to.replace="lower", replaces the lower triangle of a square matrix with its upper triangle.
   # If triangle.to.replace="upper", replaces the upper triangle of a square matrix with its lower triangle.

   if (nrow(m) != ncol(m)) stop("Supplied matrix must be square.")
   if      (tolower(triangle.to.replace) == "lower") tri <- lower.tri(m)
   else if (tolower(triangle.to.replace) == "upper") tri <- upper.tri(m)
   else stop("triangle.to.replace must be set to 'lower' or 'upper'.")
   m[tri] <- t(m)[tri]
   return(m)
}

GeoDistanceInMetresMatrix <- function(df.geopoints){
   # Returns a matrix (M) of distances between geographic points.
   # M[i,j] = M[j,i] = Distance between (df.geopoints$lat[i], df.geopoints$lon[i]) and
   # (df.geopoints$lat[j], df.geopoints$lon[j]).
   # The row and column names are given by df.geopoints$name.

   GeoDistanceInMetres <- function(g1, g2){
      # Returns a vector of distances. (But if g1$index > g2$index, returns zero.)
      # The 1st value in the returned vector is the distance between g1[[1]] and g2[[1]].
      # The 2nd value in the returned vector is the distance between g1[[2]] and g2[[2]]. Etc.
      # Each g1[[x]] or g2[[x]] must be a list with named elements "index", "lat" and "lon".
      # E.g. g1 <- list(list("index"=1, "lat"=12.1, "lon"=10.1), list("index"=3, "lat"=12.1, "lon"=13.2))
      DistM <- function(g1, g2){
         return(ifelse(g1$index > g2$index, 0, gdist(lat.1=g1$lat, lon.1=g1$lon, lat.2=g2$lat, lon.2=g2$lon, units="m")))
      }
      return(mapply(DistM, g1, g2))
   }

   n.geopoints <- nrow(df.geopoints)

   # The index column is used to ensure we only do calculations for the upper triangle of points
   df.geopoints$index <- 1:n.geopoints

   # Create a list of lists
   list.geopoints <- by(df.geopoints[,c("index", "lat", "lon")], 1:n.geopoints, function(x){return(list(x))})

   # Get a matrix of distances (in metres)
   mat.distances <- ReplaceLowerOrUpperTriangle(outer(list.geopoints, list.geopoints, GeoDistanceInMetres), "lower")

   # Set the row and column names
   rownames(mat.distances) <- df.geopoints$CityTown
   colnames(mat.distances) <- df.geopoints$CityTown

   return(mat.distances)
}

T21Towns = read.csv("~/NYU Coursework/Statistical Consulting_Fall17/PolicyDiffusion/Data/MA21_lonlat.csv")
NoT21Towns = read.csv("~/NYU Coursework/Statistical Consulting_Fall17/PolicyDiffusion/Data/NoT21Towns_lonlat.csv")

T21Towns$CityTown = gsub(" , Massachusetts","",x = T21Towns$CityTown)
NoT21Towns$CityTown = gsub(" , Massachusetts","",x = NoT21Towns$CityTown)

# Combine
AllTowns = rbind(T21Towns,NoT21Towns)[,-1]

# Generate the distance matrix in km
TownDistance_km = round(GeoDistanceInMetresMatrix(AllTowns) / 1000)

TownDistance_km[1:10,1:10]
```


NEXT LEVEL RATIO GENERATING FUNCTION:

```{r}
NearbyT21Ratios = function(distmatrix, T21List,distance = 80){
  Indistance = apply(distmatrix,1,function(x) x <= distance & x != 0)
  TotalNear = apply(Indistance,1,function(x) sum(x))
  
  NearbyF = function(distcol){
    sum(names(distcol)[which(distcol == TRUE)] %in% T21List)
  }
  NearbyT21 = apply(Indistance,2,NearbyF)
  
  RatioMatrix = round(NearbyT21/TotalNear,3)
  
  #Fix up and return as data frame
  RatioMatrix = data.frame(RatioMatrix)
  names(RatioMatrix) = "Nearby T21 Ratio"
  require(tibble)
  RatioMatrix = rownames_to_column(RatioMatrix)
  names(RatioMatrix)[1] = "CityTown"
  return(RatioMatrix)
}

T21Ratios = NearbyT21Ratios(TownDistance_km,T21Towns$CityTown,distance = 80)
T21Ratios

#write.csv(T21Ratios,"../../Data/T21Ratios.csv")
```

## We can alternatively look at the top somenumber of closest neighbors instead:

```{r}
TopT21Ratios = function(distmatrix, T21List,HowMany = 10){
  
  Indistance = matrix(rep(0,ncol(distmatrix)^2),ncol = ncol(distmatrix))
  for(i in 1:ncol(distmatrix)){
    Indistance[sort(distmatrix[,i], index.return = TRUE)$ix[2:(HowMany+1)],i] = 1
  }
  
  colnames(Indistance) = colnames(distmatrix)
  rownames(Indistance) = rownames(distmatrix)
  
  
  NearbyF = function(distcol){
    sum(names(distcol)[which(distcol == TRUE)] %in% T21List)
  }
  NearbyT21 = apply(Indistance,2,NearbyF)
  
  RatioMatrix = round(NearbyT21/HowMany,3)
  
  #Fix up and return as data frame
  RatioMatrix = data.frame(RatioMatrix)
  names(RatioMatrix) = "Nearby T21 Ratio"
  require(tibble)
  RatioMatrix = rownames_to_column(RatioMatrix)
  names(RatioMatrix)[1] = "CityTown"
  return(RatioMatrix)
}

Nearest10Ratio = TopT21Ratios(TownDistance_km,T21Towns$CityTown, HowMany = 10)
Nearest10Ratio
```

Let's get all the years and Merge.

```{r}
dat = read.csv("~/NYU Coursework/Statistical Consulting_Fall17/PolicyDiffusion/Data/matowndistyear.csv")
'%!in%' <- function(x,y)!('%in%'(x,y))


GenerateRatios = function(yr,dist = 80){
  T21Towns1 = left_join(dat %>% filter(year %in% yr),AllTowns,by = c('TownName' = 'CityTown'))[,-c(1,2,4,5)]
  names(T21Towns1)[1]= "CityTown"
  NoT21Towns1 = AllTowns %>% filter(CityTown %!in% T21Towns1$CityTown)
  AllTowns1 = rbind(T21Towns1,NoT21Towns1)
  TownDistance_km1 = round(GeoDistanceInMetresMatrix(AllTowns) / 1000)
  T21Ratios1 = data.frame(NearbyT21Ratios(TownDistance_km1,T21Towns1$CityTown,distance = dist))
  return(T21Ratios1)
}


#2005
T21Ratios2005 = GenerateRatios(2005)
T21Ratios2005$year = 2005

#2006
T21Ratios2006 = GenerateRatios(2006)
T21Ratios2006$year = 2006

#2007
T21Ratios2007 = GenerateRatios(2007)
T21Ratios2007$year = 2007

#2008
T21Ratios2008 = GenerateRatios(2008)
T21Ratios2008$year = 2008

#2009
T21Ratios2009 = GenerateRatios(2009)
T21Ratios2009$year = 2009

#2010
T21Ratios2010 = GenerateRatios(2010)
T21Ratios2010$year = 2010

#2011
T21Ratios2011 = GenerateRatios(2011)
T21Ratios2011$year = 2011

#2012
T21Ratios2012 = GenerateRatios(2012)
T21Ratios2012$year = 2012

#2013
T21Ratios2013 = GenerateRatios(2013)
T21Ratios2013$year = 2013

#2014
T21Ratios2014 = GenerateRatios(2014)
T21Ratios2014$year = 2014

#2015
T21Ratios2015 = GenerateRatios(2015)
T21Ratios2015$year = 2015

#2016
T21Ratios2016 = GenerateRatios(2016)
T21Ratios2016$year = 2016

#2017
T21Ratios2017 = GenerateRatios(2017)
T21Ratios2017$year = 2017

#2018
T21Ratios2018 = GenerateRatios(2018)
T21Ratios2018$year = 2018


ALLRATIO = rbind(T21Ratios2005,T21Ratios2006,T21Ratios2007,T21Ratios2008,T21Ratios2009,T21Ratios2010,T21Ratios2011,T21Ratios2012,T21Ratios2013,T21Ratios2014,T21Ratios2015,T21Ratios2016,T21Ratios2017,T21Ratios2018)


#write.csv(ALLRATIO,"./AllT21Ratios.csv")

#write.csv(T21Ratios2005,"./T21Ratios2005.csv")
#write.csv(T21Ratios2006,"./T21Ratios2006.csv")
#write.csv(T21Ratios2007,"./T21Ratios2007.csv")
#write.csv(T21Ratios2008,"./T21Ratios2008.csv")
#write.csv(T21Ratios2009,"./T21Ratios2009.csv")
#write.csv(T21Ratios2010,"./T21Ratios2010.csv")
#write.csv(T21Ratios2011,"./T21Ratios2011.csv")
#write.csv(T21Ratios2012,"./T21Ratios2012.csv")
#write.csv(T21Ratios2013,"./T21Ratios2013.csv")
#write.csv(T21Ratios2014,"./T21Ratios2014.csv")
#write.csv(T21Ratios2015,"./T21Ratios2015.csv")
#write.csv(T21Ratios2016,"./T21Ratios2016.csv")
#write.csv(T21Ratios2017,"./T21Ratios2017.csv")
#write.csv(T21Ratios2018,"./T21Ratios2018.csv")
```

For the Top 10 Ratios

```{r}
GenerateTopRatios = function(yr,HowMan = 10){
  T21Towns1 = left_join(dat %>% filter(year %in% yr),AllTowns,by = c('TownName' = 'CityTown'))[,-c(1,2,4,5)]
  names(T21Towns1)[1]= "CityTown"
  NoT21Towns1 = AllTowns %>% filter(CityTown %!in% T21Towns1$CityTown)
  AllTowns1 = rbind(T21Towns1,NoT21Towns1)
  TownDistance_km1 = round(GeoDistanceInMetresMatrix(AllTowns) / 1000)
  T21Ratios1 = TopT21Ratios(TownDistance_km1,T21Towns1$CityTown,HowMany = HowMan)
  return(T21Ratios1)
}


#2005
T21TopRatios2005 = GenerateTopRatios(2005)
T21TopRatios2005$year = 2005

#2006
T21TopRatios2006 = GenerateTopRatios(2006)
T21TopRatios2006$year = 2006

#2007
T21TopRatios2007 = GenerateTopRatios(2007)
T21TopRatios2007$year = 2007

#2008
T21TopRatios2008 = GenerateTopRatios(2008)
T21TopRatios2008$year = 2008

#2009
T21TopRatios2009 = GenerateTopRatios(2009)
T21TopRatios2009$year = 2009

#2010
T21TopRatios2010 = GenerateTopRatios(2010)
T21TopRatios2010$year = 2010

#2011
T21TopRatios2011 = GenerateTopRatios(2011)
T21TopRatios2011$year = 2011

#2012
T21TopRatios2012 = GenerateTopRatios(2012)
T21TopRatios2012$year = 2012

#2013
T21TopRatios2013 = GenerateTopRatios(2013)
T21TopRatios2013$year = 2013

#2014
T21TopRatios2014 = GenerateTopRatios(2014)
T21TopRatios2014$year = 2014

#2015
T21TopRatios2015 = GenerateTopRatios(2015)
T21TopRatios2015$year = 2015

#2016
T21TopRatios2016 = GenerateTopRatios(2016)
T21TopRatios2016$year = 2016

#2017
T21TopRatios2017 = GenerateTopRatios(2017)
T21TopRatios2017$year = 2017

#2018
T21TopRatios2018 = GenerateTopRatios(2018)
T21TopRatios2018$year = 2018

ALLTopRATIO = rbind(T21TopRatios2005,T21TopRatios2006,T21TopRatios2007,T21TopRatios2008,T21TopRatios2009,T21TopRatios2010,T21TopRatios2011,T21TopRatios2012,T21TopRatios2013,T21TopRatios2014,T21TopRatios2015,T21TopRatios2016,T21TopRatios2017,T21TopRatios2018)

#write.csv(ALLTopRATIO,"./AllT21TopRatios.csv")
```


# Road Distance?

```{r}
require(gmapsdistance)

gmapsdistancefix <- function (origin, destination, combinations = "all", mode, key = get.api.key(), 
    shape = "wide", avoid = "", departure = "now", dep_date = "", 
    dep_time = "", traffic_model = "best_guess", arrival = "", 
    arr_date = "", arr_time = "") 
{
  require(RCurl)
  require(XML)
    if (!(mode %in% c("driving", "walking", "bicycling", "transit"))) {
        stop("Mode of transportation not recognized. Mode should be one of ", 
            "'bicycling', 'transit', 'driving', 'walking' ")
    }
    if (!(combinations %in% c("all", "pairwise"))) {
        stop("Combinations between origin and destination not recognized. Combinations should be one of ", 
            "'all', 'pairwise' ")
    }
    if (!(avoid %in% c("", "tolls", "highways", "ferries", "indoor"))) {
        stop("Avoid parameters not recognized. Avoid should be one of ", 
            "'tolls', 'highways', 'ferries', 'indoor' ")
    }
    if (!(traffic_model %in% c("best_guess", "pessimistic", "optimistic"))) {
        stop("Traffic model not recognized. Traffic model should be one of ", 
            "'best_guess', 'pessimistic', 'optimistic'")
    }
    seconds = "now"
    seconds_arrival = ""
    UTCtime = strptime("1970-01-01 00:00:00", "%Y-%m-%d %H:%M:%OS", 
        tz = "GMT")
    min_secs = round(as.numeric(difftime(as.POSIXlt(Sys.time(), 
        "GMT"), UTCtime, units = "secs")))
    if (dep_date != "" && dep_time != "") {
        depart = strptime(paste(dep_date, dep_time), "%Y-%m-%d %H:%M:%OS", 
            tz = "GMT")
        seconds = round(as.numeric(difftime(depart, UTCtime, 
            units = "secs")))
    }
    if (departure != "now") {
        seconds = departure
    }
    if (departure != "now" && departure < min_secs) {
        stop("The departure time has to be some time in the future!")
    }
    if (dep_date != "" && dep_time == "") {
        stop("You should also specify a departure time in the format HH:MM:SS UTC")
    }
    if (dep_date == "" && dep_time != "") {
        stop("You should also specify a departure date in the format YYYY-MM-DD UTC")
    }
    if (dep_date != "" && dep_time != "" && seconds < min_secs) {
        stop("The departure time has to be some time in the future!")
    }
    if (arr_date != "" && arr_time != "") {
        arriv = strptime(paste(arr_date, arr_time), "%Y-%m-%d %H:%M:%OS", 
            tz = "GMT")
        seconds_arrival = round(as.numeric(difftime(arriv, UTCtime, 
            units = "secs")))
    }
    if (arrival != "") {
        seconds_arrival = arrival
    }
    if (arrival != "" && arrival < min_secs) {
        stop("The arrival time has to be some time in the future!")
    }
    if (arr_date != "" && arr_time == "") {
        stop("You should also specify an arrival time in the format HH:MM:SS UTC")
    }
    if (arr_date == "" && arr_time != "") {
        stop("You should also specify an arrival date in the format YYYY-MM-DD UTC")
    }
    if (arr_date != "" && arr_time != "" && seconds_arrival < 
        min_secs) {
        stop("The arrival time has to be some time in the future!")
    }
    if ((dep_date != "" || dep_time != "" || departure != "now") && 
        (arr_date != "" || arr_time != "" || arrival != "")) {
        stop("Cannot input departure and arrival times. Only one can be used at a time. ")
    }
    if (combinations == "pairwise" && length(origin) != length(destination)) {
        stop("Size of origin and destination vectors must be the same when using the option: combinations == 'pairwise'")
    }
    if (combinations == "all") {
        data = expand.grid(or = origin, de = destination)
    }
    else if (combinations == "pairwise") {
        data = data.frame(or = origin, de = destination)
    }
    n = dim(data)
    n = n[1]
    data$Time = NA
    data$Distance = NA
    data$status = "OK"
    avoidmsg = ""
    if (avoid != "") {
        avoidmsg = paste0("&avoid=", avoid)
    }
    for (i in 1:1:n) {
        url = paste0("maps.googleapis.com/maps/api/distancematrix/xml?origins=", 
            data$or[i], "&destinations=", data$de[i], "&mode=", 
            mode, "&sensor=", "false", "&units=metric", "&departure_time=", 
            seconds, "&traffic_model=", traffic_model, avoidmsg)
        if (!is.null(key)) {
            key = gsub(" ", "", key)
            url = paste0("https://", url, "&key=", key)
        }
        else {
            url = paste0("http://", url)
        }
        webpageXML = xmlParse(getURL(url))
        results = xmlChildren(xmlRoot(webpageXML))
        request.status = as(unlist(results$status[[1]]), "character")
        if (!is.null(results$error_message)) {
            stop(paste(c("Google API returned an error: ", xmlValue(results$error_message)), 
                sep = ""))
        }
        if (request.status == "REQUEST_DENIED") {
            set.api.key(NULL)
            data$status[i] = "REQUEST_DENIED"
        }
        rowXML = xmlChildren(results$row[[1L]])
        Status = as(rowXML$status[1]$text, "character")
        if (Status == "ZERO_RESULTS") {
            data$status[i] = "ROUTE_NOT_FOUND"
        }
        if (Status == "NOT_FOUND") {
            data$status[i] = "PLACE_NOT_FOUND"
        }
        if (Status == "OVER_QUERY_LIMIT") {
            stop("You have exceeded your allocation of API requests for today.")
        }
        if (data$status[i] == "OK") {
            data$Distance[i] = as(rowXML$distance[1]$value[1]$text, 
                "numeric")
            dur = grep("^duration$", names(rowXML), value = TRUE)
            data$Time[i] = as(rowXML[[dur]][1L]$value[1L]$text, 
                "numeric")
        }
    }
    datadist = data[c("or", "de", "Distance")]
    datatime = data[c("or", "de", "Time")]
    datastat = data[c("or", "de", "status")]
    if (n > 1) {
        if (shape == "wide" && combinations == "all") {
            Distance = reshape(datadist, timevar = "de", idvar = c("or"), 
                direction = "wide")
            Time = reshape(datatime, timevar = "de", idvar = c("or"), 
                direction = "wide")
            Stat = reshape(datastat, timevar = "de", idvar = c("or"), 
                direction = "wide")
        }
        else {
            Distance = datadist
            Time = datatime
            Stat = datastat
        }
    }
    else {
        Distance = data$Distance[i]
        Time = data$Time[i]
        Stat = data$status[i]
    }
    output = list(Time = Time, Distance = Distance, Status = Stat)
    return(output)
}

set.api.key("AIzaSyBdc25d1AoZRHCM01zXiEkkMp55Bbso-MQ")
set.api.key("AIzaSyD3AK50wTG7tL6hNfap_tjJ_PNqtGpPd5o") # Zarni's API code

Towns <- gsub(" ","+",paste(AllTowns$CityTown,"MA"))

gmap_results1 <- gmapsdistancefix(origin=Towns[1:39], 
                       destination=Towns, 
                       mode="driving",
                       #departure=as.integer(as.POSIXct('2017-11-19 22:00:00 EST')), 
                       traffic_model="best_guess",
                       key = get.api.key())

gmap_results2 <- gmapsdistancefix(origin=Towns[40:79], 
                       destination=Towns, 
                       mode="driving",
                       #departure=as.integer(as.POSIXct('2017-11-19 22:00:00 EST')), 
                       traffic_model="best_guess",
                       key = get.api.key())

gmap_results3 <- gmapsdistancefix(origin=Towns[80:119], 
                       destination=Towns, 
                       mode="driving",
                       #departure=as.integer(as.POSIXct('2017-11-19 22:00:00 EST')), 
                       traffic_model="best_guess",
                       key = get.api.key())

gmap_results4 <- gmapsdistancefix(origin=Towns[120:159], 
                       destination=Towns, 
                       mode="driving",
                       #departure=as.integer(as.POSIXct('2017-11-19 22:00:00 EST')), 
                       traffic_model="best_guess",
                       key = get.api.key())

gmap_results5 <- gmapsdistancefix(origin=Towns[160:199], 
                       destination=Towns, 
                       mode="driving",
                       #departure=as.integer(as.POSIXct('2017-11-19 22:00:00 EST')), 
                       traffic_model="best_guess",
                       key = get.api.key())

gmap_results6 <- gmapsdistancefix(origin=Towns[200:239], 
                       destination=Towns, 
                       mode="driving",
                       #departure=as.integer(as.POSIXct('2017-11-19 22:00:00 EST')), 
                       traffic_model="best_guess",
                       key = get.api.key())

gmap_results7 <- gmapsdistancefix(origin=Towns[240:279], 
                       destination=Towns, 
                       mode="driving",
                       #departure=as.integer(as.POSIXct('2017-11-19 22:00:00 EST')), 
                       traffic_model="best_guess",
                       key = get.api.key())

gmap_results8 <- gmapsdistancefix(origin=Towns[280:319], 
                       destination=Towns, 
                       mode="driving",
                       #departure=as.integer(as.POSIXct('2017-11-19 22:00:00 EST')), 
                       traffic_model="best_guess",
                       key = get.api.key())

gmap_results9 <- gmapsdistancefix(origin=Towns[320:351], 
                       destination=Towns, 
                       mode="driving",
                       #departure=as.integer(as.POSIXct('2017-11-19 22:00:00 EST')), 
                       traffic_model="best_guess",
                       key = get.api.key())

```

```{r}
results = gmapsdistance(origin = c("Washington +DC", "New+York+NY"), 
                         destination = c("Washington+DC", "Austin+TX"), 
                         mode = "driving", 
                         departure = 1514742000,
                         traffic_model = "pessimistic", 
                         shape = "long")
 

results=gmapsdistancefix(origin = Towns[1:5], 
                         destination = Towns[1:10], 
                         mode = "driving",
                         traffic_model = "pessimistic", 
                         shape = "long",
                      key = get.api.key())

```
